### ISSUE TITLE
Once it boots, it says wifi is disconnected.

### ISSUE THREAD

**Issue by chriss823** [Pixilate/SMPatches-DL#2]
The boot up error is fixed for me but now I am getting this error. It boots up fine but on the screen it says, wifi is disconnected. Press B to go back to home menu. At the bottom left it says v1.1 I don't know if that matters or not.

**Comment by Pixilate** [comment]
I'm thinking this is a LPP-3DS issue, as I'm having the issue as well

**Comment by Pixilate** [comment]
Issue has been fixed (finally)
