### ISSUE TITLE
Black screen after booting up

### ISSUE THREAD

**Issue by User13181408200115** [Pixilate/SMPatches-DL#3]
New nintendo 3ds
Luma CFW 7.1
        Autoboot sysnand, Enable loading external firms and modules & enable game patching
sysnand 11.4
Pokemon Sun
video of the error:
https://www.youtube.com/watch?v=pgD0I6a7cDk 
I can exit from the black screen by pressing "b"

**Comment by Pixilate** [comment]
Not an issue. Simply means it finished

**Comment by User13181408200115** [comment]
I thought the application allowed you to pick and choose multiple patches but I understand now, you were correct by the way it did apply the no lines patch
